name: continuous-integration
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extension-csv: mbstring,bcmath,curl,gettext,exif,intl
          ini-values-csv: pcov.directory=./src/
          coverage: pcov
      - name: Composer install
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: PHP Coding Standards
        run: composer run ecs-check
      - name: PHPUnit
        run: ./vendor/bin/phpunit --coverage-clover=coverage.clover
      - name: Upload Coverage report
        run: vendor/bin/ocular code-coverage:upload --access-token="${SCRUTINIZER_ACCESS_TOKEN}" --format=php-clover ./coverage.clover
        env:
          SCRUTINIZER_ACCESS_TOKEN: ${{ secrets.SCRUTINIZER_ACCESS_TOKEN }}
